### ISSUE TITLE
StyleProvider migration

### ISSUE THREAD

**Issue by rhigueraa** [escoz/QuickDialog#576]
Hi, I just updated from 0.7 to 0.9 and noticed style provider is gone...
I read that now you have to assign QAppearance to each root but...
and my question is...
can you still call
- (void)cell:(UITableViewCell *)cell willAppearForElement:(QElement *)element atIndexPath:(NSIndexPath *)indexPath

in any way ?? i've got all my design heavily based on this method... and I would not like to set a QAppearance for each case of my app...

or does anyone have a practical solution ? 

Thanks!

**Comment by katche70** [comment]
i update to latest version. but it always said:
Property 'appearance' not found on object of type 'QLabelElement *'

What is wrong? in demo Version all is fine. 
It is necessary to include QAppearance?
